version: "3.0"
services:
  stag-utility-service:
    image: ${ECR_REGISTRY}/${IMAGE_NAME}:${TAG}
    ports:
      - 7300:7300
      - 7301:7301
    environment:
      - GRPC_PORT=7300
      - HTTP_PORT=7301
      - DB_HOST=staging-postgre
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=utility-service
    networks:
      - grpc_network
networks:
  grpc_network:
    external: true