version: "3.0"
services:
  app:
    image: ${ECR_REGISTRY}/${IMAGE_NAME}:${COMMIT_HASH}
    ports:
      - 9300:9300
      - 9301:9301
    environment:
      - GRPC_PORT=9300
      - HTTP_PORT=9301
      - DB_HOST=prod-postgre
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=utility-service
    networks:
      - grpc_network
networks:
  grpc_network:
    external: true